### ISSUE TITLE
Add commit hooks

### ISSUE THREAD

**Issue by MichaelCurrin** [MichaelCurrin/py-project-template#11]
From Poetry

```yaml
repos:
  - repo: https://github.com/psf/black
    rev: stable
    hooks:
      - id: black

  - repo: https://gitlab.com/pycqa/flake8
    rev: 3.7.8
    hooks:
      - id: flake8

  - repo: https://github.com/timothycrosley/isort
    rev: 4.3.21-2
    hooks:
      - id: isort
        additional_dependencies: [toml]
        exclude: ^.*/?setup\.py$

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: trailing-whitespace
        exclude: ^tests/.*/fixtures/.*
      - id: end-of-file-fixer
        exclude: ^tests/.*/fixtures/.*
      - id: debug-statements
```
